name: MoleHunt
version: 1.3
main: com.boes.molehunt.Molehunt
api-version: "1.21"
commands:
  molehunt:
    description: Main command for Mole Hunt
    usage: /molehunt <start|stop|reload|spectate|leave>
    permission: molehunt.admin

permissions:
  molehunt.admin:
    default: op
